version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "49154:5432"
    environment:
      POSTGRES_PASSWORD: postgres




# services:
#   postgres:
#     image: postgres:latest
#     environment:
#       - POSTGRES_PASSWORD=postgrespw
#     ports:
#       - 5432:5432
